#### Install Liabraries

#### Load DataSet

In [2]:
import numpy as np

# A class to represent our Logistic Regression model
class LogisticRegression:
    
    # The __init__ method is called when we create a new instance of the class.
    # It initializes the learning rate and the number of training iterations.
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None # 'w' in formulas
        self.bias = None    # 'b' in formulas

    # The sigmoid function, which is our hypothesis
    def _sigmoid(self, z):
        # Formula: 1 / (1 + e^(-z))
        return 1 / (1 + np.exp(-z))

    # The 'fit' method trains the model using gradient descent
    def fit(self, X, y):
        # Get number of samples (rows) and features (columns)
        n_samples, n_features = X.shape

        # Initialize weights and bias to zeros
        self.weights = np.zeros(n_features)
        self.bias = 0

        # Gradient Descent: loop for the specified number of iterations
        for _ in range(self.n_iters):
            # Calculate the linear part of the model
            # Formula: z = X.w + b
            linear_model = np.dot(X, self.weights) + self.bias
            
            # Apply the sigmoid function to get predicted probabilities
            # Formula: h(z)
            y_predicted = self._sigmoid(linear_model)

            # Calculate the gradients (derivatives) of the cost function
            # Formula for dw: (1/m) * X^T * (h(X) - y)
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            # Formula for db: (1/m) * sum(h(x) - y)
            db = (1 / n_samples) * np.sum(y_predicted - y)

            # Update the weights and bias using the update rule
            # Formula: w := w - alpha * dw
            self.weights -= self.lr * dw
            # Formula: b := b - alpha * db
            self.bias -= self.lr * db

    # The 'predict' method makes predictions on new, unseen data
    def predict(self, X):
        # Calculate the linear model and pass it through the sigmoid function
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self._sigmoid(linear_model)
        
        # Classify the results. If probability is > 0.5, predict 1 (High Yield), else 0 (Low Yield).
        y_predicted_cls = [1 if i > 0.5 else 0 for i in y_predicted]
        return np.array(y_predicted_cls)


# --- USAGE EXAMPLE ---

# 1. Prepare the data
# Let's use more data points for a better example.
rainfall =     [450, 600, 800, 300, 550, 750, 250, 400]
fertilizer =   [100, 120, 90,  150, 110, 130, 160, 80]
soil_quality = [7,   6,   5,   8,   7,   6,   8,   7]

# Target variable (1 = High Yield, 0 = Low Yield)
y = np.array([1, 1, 1, 0, 1, 1, 0, 0])

# Combine features into a single 2D array (our X matrix)
# Each row is a sample, each column is a feature.
X = np.array([rainfall, fertilizer, soil_quality]).T

print("Feature Matrix X (first 5 rows):\n", X[:5])
print("\nTarget Vector y:\n", y)


# 2. Train the model
# Create an instance of our LogisticRegression class
# We'll use a slightly higher learning rate and more iterations for this data
model = LogisticRegression(learning_rate=0.001, n_iters=10000)

# Train the model on our data
model.fit(X, y)

# 3. Make predictions
# Let's create a new data point to test the model
# rainfall=500, fertilizer=115, soil_quality=6
new_crop_data = np.array([[500, 115, 6]]) 
predictions = model.predict(X) # Make predictions on the training data to see how well it learned
new_prediction = model.predict(new_crop_data)


# 4. Show the results
print("\n--- Model Training Complete ---")
print(f"Learned Weights: {model.weights}")
print(f"Learned Bias: {model.bias}")

print(f"\nPredictions on original data: {predictions}")
print(f"Actual labels of original data: {y}")

print(f"\nPrediction for new crop data [500, 115, 6]: {new_prediction[0]} (1=High, 0=Low)")

Feature Matrix X (first 5 rows):
 [[450 100   7]
 [600 120   6]
 [800  90   5]
 [300 150   8]
 [550 110   7]]

Target Vector y:
 [1 1 1 0 1 1 0 0]

--- Model Training Complete ---
Learned Weights: [ 0.17504945 -0.5866246  -2.17190923]
Learned Bias: -0.2683493638378833

Predictions on original data: [1 1 1 0 1 1 0 1]
Actual labels of original data: [1 1 1 0 1 1 0 0]

Prediction for new crop data [500, 115, 6]: 1 (1=High, 0=Low)
