In [4]:
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 3, 5]
])

W1 = np.random.randn(3, 4)
b1 = np.random.randn(1, 4)

W2 = np.random.randn(4, 1)
b2 = np.random.randn(1, 1)

W2 = np.random.randn()
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

z1 = np.dot(X, W1) + b1
a1 = sigmoid(z1)


z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

print("output predictions: \n", a2)

output predictions: 
 [[0.44489913 0.62582057 0.62757937 0.44699758]
 [0.44221927 0.62760661 0.62761364 0.44197088]
 [0.44198506 0.62761362 0.62761365 0.44196298]
 [0.44212141 0.62725014 0.62761348 0.4434775 ]]


In [ ]:
import numpy as np

# Sample dataset (4 examples, each with 3 features)
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 3, 5]
])

W1 = np.random.randn(3, 5)
b1 = np.random.randn(1, 5)

W2 = np.random.randn(5, 4)
b2 = np.random.randn(1, 4)

W3 = np.random.randn(4, 1)
b3 = np.random.randn(1,1)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

z1 = np.dot(X, W1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

z3 = np.dot(a2, W3) + b3
a3 = sigmoid(z3)



print(f"Output prediction: {a3}")

Output prediction: [[0.88439017]
 [0.88435051]
 [0.88435145]
 [0.88432814]]
